# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Joinings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('complection_date', models.CharField(max_length=150)),
                ('date_join', models.CharField(max_length=2500)),
                ('course_fee', models.CharField(max_length=250)),
                ('instructor', models.CharField(max_length=250)),
                ('aadhar_number', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=2500)),
                ('email', models.CharField(max_length=2500)),
                ('remarks', models.CharField(max_length=2500)),
                ('Status', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=250)),
                ('st_mobile', models.CharField(max_length=250)),
                ('st_email', models.CharField(max_length=150)),
                ('st_course', models.CharField(max_length=2500)),
                ('st_sourse', models.CharField(max_length=250)),
                ('st_lead_status', models.CharField(max_length=250)),
                ('st_demo_date', models.CharField(max_length=150)),
                ('st_counsler', models.CharField(max_length=2500)),
                ('st_remarks', models.CharField(max_length=2500)),
            ],
        ),
    ]
